### ISSUE TITLE
[Function Request]WorldCoordsToScreen(player.color)

### ISSUE THREAD

**Issue by Jophire** [Berserk-Games/Tabletop-Simulator-API#102]
Can we get a function that returns a players cursor world position converted to screen coords for use with XML; or a function that returns the players current Camera transform.

**Comment by nabbydude** [comment]
Looks like your issue pertains to Tabletop Simulator itself, and not the API documentation, which this repo is for. Check out [https://tabletopsimulator.nolt.io/](https://tabletopsimulator.nolt.io/) to submit and vote for bugs, suggestions, and requests for the game itself. If you just have a question about the game, also check out [The Official Tabletop Simulator Discord Server](https://discord.com/invite/tabletopsimulator), the community may be able to answer it.
