### ISSUE TITLE
bug: spawnObjects(...)

### ISSUE THREAD

**Issue by ytzzzz** [Berserk-Games/Tabletop-Simulator-API#107]
here is code.
```
    spawnParams = {
        type = '3DText',
        position          = {x=0, y=3, z=-5},
        rotation          = {x=0, y=90, z=0},
        scale             = {x=2, y=2, z=2},
        sound             = false,
        snap_to_grid      = true,
        callback_function = function(obj) spawn_callback(obj, "Bear", "Green") end
    }
    spawnObject(spawnParams)

function spawn_callback(object_spawned, name, color)
    object_spawned.setName(name)
    object_spawned.setColorTint(color)
end
```

when type = '3DText', cannot trigger callback correctly.
however, when type = "rpg_BEAR" or other something, can trigger callback.
I don't know why.

**Comment by nabbydude** [comment]
Looks like your issue pertains to Tabletop Simulator itself, and not the API documentation, which this repo is for. Check out [https://tabletopsimulator.nolt.io/](https://tabletopsimulator.nolt.io/) to submit and vote for bugs, suggestions, and requests for the game itself. If you just have a question about the game, also check out [The Official Tabletop Simulator Discord Server](https://discord.com/invite/tabletopsimulator), the community may be able to answer it.
