### ISSUE TITLE
UI Buttons (and other elements) don't toggle Grid Projection

### ISSUE THREAD

**Issue by adamgede** [Berserk-Games/Tabletop-Simulator-API#108]
If you add UI elements to a Notecard, and toggle off the Grid Projection for the card, the UI elements still show the grid on them.

For example, if you take the following UI elements and put it on a Notecard, you'll see the Grid Projection showing up on those buttons.

=========================================

`<!-- Background for buttons -->`
`<Image width="107" height="113.4" color="#000000A0" offsetXY="4 -6.1"></Image>`

`<!-- Text for Totals -->`
`<Text width="150" height="30" offsetXY="53.4 0" fontsize="25" fontStyle="Bold" scale="0.25 0.25" rotation="0 0 270" color="#ffffff">0 / 0</Text>`

`<!-- Buttons on the right: Page up, up, down, and Page Down -->`
`<Button width="30" height="75" offsetXY="53.7 41.1" padding="2 0 0 5" fontsize="25" fontStyle="Bold" scale="0.25 0.25" tooltip="Previous Page" color="#8080ff" tooltipPosition="Right" tooltipBorderColor="#8080ff" tooltipOffset="-5">▲&#10;▲</Button>`
`<Button width="30" height="40" offsetXY="53.7 26.1" padding="2 0 0 5" fontsize="25" fontStyle="Bold" scale="0.25 0.25" tooltip="Up One" color="#80ffff" tooltipPosition="Right" tooltipBorderColor="#80ffff" tooltipOffset="-5">▲</Button>`
`<Button width="30" height="40" offsetXY="53.7 -26.1" padding="2 0 0 5" fontsize="25" fontStyle="Bold" scale="0.25 0.25" tooltip="Down One" color="#80ffff" tooltipPosition="Right" tooltipBorderColor="#80ffff" tooltipOffset="-5">▼</Button>`
`<Button width="30" height="75" offsetXY="53.7 -41.1" padding="2 0 0 5" fontsize="25" fontStyle="Bold" scale="0.25 0.25" tooltip="Next Page" color="#8080ff" tooltipPosition="Right" tooltipBorderColor="#8080ff" tooltipOffset="-5">▼&#10;▼</Button>`

`<!-- Buttons on the bottom: Load, Move, Alert, and Next -->`
`<Button width="120" height="50" offsetXY="-35.5 -56.25" fontsize="22" fontStyle="Bold" scale="0.25 0.25"
   tooltip="Load Information" colors="#ffffff|#cc0000|#00cc00|#0000cc" tooltipPosition="Below" tooltipOffset="-5"
   tooltipBorderColor="#ffffff" id="TestButton" grid_projection="false">Load Information</Button>`
`<Button width="75" height="50" offsetXY="-5 -56.25" fontsize="22" fontStyle="Bold" scale="0.25 0.25"
   tooltip="Reorder this item" color="#ffffff" tooltipPosition="Below" tooltipOffset="-5" id="bMove"
   tooltipBorderColor="#ffffff">Move</Button>`
`<Button width="75" height="50" offsetXY="15 -56.25" fontsize="22" fontStyle="Bold" scale="0.25 0.25"
   tooltip="Send message" color="#ffffff" tooltipPosition="Below" tooltipOffset="-5"
   tooltipBorderColor="#ffffff">Alert</Button>`
`<Button width="75" height="50" offsetXY="41 -56.25" fontsize="22" fontStyle="Bold" scale="0.25 0.25"
   tooltip="Move item and send a message" color="#ffffff" tooltipPosition="Below" tooltipOffset="-5"
   tooltipBorderColor="#ffffff">Next</Button>`

**Comment by nabbydude** [comment]
Looks like your issue pertains to Tabletop Simulator itself, and not the API documentation, which this repo is for. Check out [https://tabletopsimulator.nolt.io/](https://tabletopsimulator.nolt.io/) to submit and vote for bugs, suggestions, and requests for the game itself.
