### ISSUE TITLE
Document deprecated features as such

### ISSUE THREAD

**Issue by nabbydude** [Berserk-Games/Tabletop-Simulator-API#113]
While not recommended to use, information on deprecated features should remain available on the API, but clearly marked as such. An incomplete list of deprecated features:

- `Timer`
- `filterObjectEnter`/`filterObjectEnterContainer`
- `Object.tag`
- `onload`

**Comment by Benjamin-Dobell** [comment]
With the exception of `onload` these are now documented as deprecated.

`onload` is omitted because I want to avoid cluttering the docs with too many deprecated APIs and searching for `onload` is going to yield results for `onLoad`.
