### ISSUE TITLE
onPlayerTurn doesn't fire in single-player games when the turn button is clicked

### ISSUE THREAD

**Issue by Urhixidur** [Berserk-Games/Tabletop-Simulator-API#117]
onPlayerTurn() fires when Turns.enable is set to true and when Turns.turn_color is set. But if you have a single player seated and that player clicks the turn button at the screen’s top, the event does not fire.

Also reported as https://tabletopsimulator.nolt.io/318

**Comment by Benjamin-Dobell** [comment]
Closing as Nolt is the correct place for bug reports.
