### ISSUE TITLE
Error on function Object.deal()

### ISSUE THREAD

**Issue by Zehir** [Berserk-Games/Tabletop-Simulator-API#15]
According the doc:
 index: Index of which Object to deal from a container.
Optional, defaults to 0. If not supplied it will deal in regular order.

So is this mean that if index = 5 I will take the fifth card from the deck?

The result ingame is to put the first card in the fifth hand of the player

**Comment by Knils** [comment]
Thanks for the report that has been fixed in the api. The index is actually a hand index not deck index.
