### ISSUE TITLE
onPlayerTurn documentation errors

### ISSUE THREAD

**Issue by WolfgangAxel** [Berserk-Games/Tabletop-Simulator-API#17]
The [onPlayerTurn()](https://api.tabletopsimulator.com/event/#onplayerturn) function description says the function executes at the end of the player's turn, when it should say it executes at the beginning.

The returned object is also listed incorrectly. It says it will return a `string` player_color, however it actually returns a reference to the `Player`. As such the example should also be updated to read as follows:

    function onPlayerTurn(player)
        print(player.color .. "'s turn starts now.")
    end

****

Also, I know this repo is only for the documentation, but I also have found a bug in the `Turns.getPreviousTurnColor()` function. It only returns an empty string, whereas `Turns.getNextTurnColor()` works as expected. I'll report it on the forums if you want this duplicated over there, but it seems like it'll probably be an easy fix.

**Comment by MisterStump** [comment]
The API was updated to reflect that. It was a typo, thank you for catching it. getPreviousTurnColor is currently bugged and we are fixing it. Sorry it was missed for so long. I hadn't realized people were posting issues here.
