### ISSUE TITLE
onSave documentation is unclear/contradictory

### ISSUE THREAD

**Issue by Benjamin-Dobell** [Berserk-Games/Tabletop-Simulator-API#20]
The documentation pertaining to `onSave` shows the value manually being set on an Object's `script_state`:

https://github.com/Berserk-Games/Tabletop-Simulator-API/blame/master/docs/event.md#L467

The documentation for `onLoad` includes example code that also shows `onSave` in use. However, it indicates that a string should be _returned_, rather than setting the `script_state` property directly on the Object:

https://github.com/Berserk-Games/Tabletop-Simulator-API/blame/master/docs/event.md#L149

Which is correct?

I'd be inclined think saving state via _return value_ makes more sense, particularly if the object is about to be destroyed, it gives you guys flexibility with your engine internals. _However_, that's just a guess.

Actually, most of the documentation seems to be missing return values. If we could get types added in a similar fashion to how it's indicated for parameters then that would be a _huge_ help. ~~I'd happily submit PRs myself, however I'm new to TTS and genuinely don't know the expected return values.~~ **EDIT:** Worked out there's only two methods with return values, PR submitted.

**Comment by AufderWelt** [comment]
@Benjamin-Dobell Hi, this issue should be closed, or?
