### ISSUE TITLE
New Vector and Color classes are missing documentation

### ISSUE THREAD

**Issue by VapidLinus** [Berserk-Games/Tabletop-Simulator-API#36]
Added in this update:
https://steamcommunity.com/games/TabletopSimulator/announcements/detail/3535809451399020344

**Comment by Benjamin-Dobell** [comment]
Added in https://github.com/Berserk-Games/Tabletop-Simulator-API/commit/44fb8e6eb839699167d783329b211c59f79890f3 and https://github.com/Berserk-Games/Tabletop-Simulator-API/commit/8b45999b744f8797ac0fd8f927d897ef708c5e91.
