### ISSUE TITLE
Base.group() does not return object reference

### ISSUE THREAD

**Issue by EpicWolverine** [Berserk-Games/Tabletop-Simulator-API#37]
According to [the documentation](https://api.tabletopsimulator.com/base/#group), `Base.group()` "returns an object reference to the deck/stack formed." However, it looks like it's instead returning an empty table. I could loop over the objects on the table to find the deck since there's only one, but that seems kind of silly when I just created the deck in the line above it.

**Comment by omniraptorr** [comment]
the signature was fixed in a recent commit
