### ISSUE TITLE
"left mouse button" does not work in vr tablet

### ISSUE THREAD

**Issue by zcaalock** [Berserk-Games/Tabletop-Simulator-API#38]
cannot click any button/link in ingame tablet view when using vr

**Comment by thebraino** [comment]
Seconding/expounding this - cannot click on buttons within a panel in VR.

**Comment by ikegami** [comment]
Issues with TTS should be reported here: https://tabletopsimulator.nolt.io/

This is for issues with the TTS API documentation.
