### ISSUE TITLE
API Intro has broken links to class documents.

### ISSUE THREAD

**Issue by Julian-O** [Berserk-Games/Tabletop-Simulator-API#45]
The documentation on page: https://api.tabletopsimulator.com/intro/ has lists of links links to documentation on Object Classes and Static Classes.

Each link is broken, because it is pointing `/intro/<classname>` rather than `/<classname>`.

E.g. the link to Clock is https://api.tabletopsimulator.com/intro/clock rather than the correct link: https://api.tabletopsimulator.com/clock

(Seems trivial to fix, but I haven't even decided to installed the TableTop Simulator as a player, let alone start forking repositories, so I will leave it to someone else.)

**Comment by Crwth** [comment]
This isn't limited to the Intro; all links in the documentation to other classes and methods are broken, because they're being generated as relative links instead of absolute ones.

**Comment by Benjamin-Dobell** [comment]
All links should be working now. If you stumble across anymore broken links. Feel free to comment here or open a new issue.
