### ISSUE TITLE
Function Request: XML utility functions.

### ISSUE THREAD

**Issue by Jophire** [Berserk-Games/Tabletop-Simulator-API#46]
returns string XML.encode(table)
returns table XML.decode(string)

Please add these utility functions. Currently am having to mess around with spawning an object, setting the xml string or table in the callback, wait a frame and then call the alternate xml get, just to convert a xml table to string and vice-versa.

**Comment by Benjamin-Dobell** [comment]
Please file feature requests at https://tabletopsimulator.nolt.io/. If you do, please elaborate on your use case, so we can better understand your motivation.
