### ISSUE TITLE
maybe an issue with xml toggles.

### ISSUE THREAD

**Issue by Nightbreez** [Berserk-Games/Tabletop-Simulator-API#52]
this happens with a normal toggle button inside of a vertical layout for me.
 <Toggle  isOn="true" text="Core Set" id = "Core" onValueChanged = "toggleTest" 
If you have two players (P1 and P2) and P1 clicks the toggle on his screen turning it to unchecked and runs the onValueChanged function it does not uncheck for P2 thus allowing P2 to uncheck the toggle on their screen running the onValueChanged function again. IDK if this is a bug or a feature because if i add something like 
function toggleTest(player,bool,id)
  if bool == "False" then
    UI.setAttribute(id, "isOn", false)
  elseif bool == "True" then
    UI.setAttribute(id, "isOn", true)
end
it then updates the toggle for everyone when one person clicks it. Figured I would report it just in case.

**Comment by nabbydude** [comment]
Looks like your issue pertains to Tabletop Simulator itself, and not the API documentation, which this repo is for. Check out [https://tabletopsimulator.nolt.io/](https://tabletopsimulator.nolt.io/) to submit and vote for bugs, suggestions, and requests for the game itself. If you just have a question about the game, also check out [The Official Tabletop Simulator Discord Server](https://discord.com/invite/tabletopsimulator), the community may be able to answer it.

**Comment by Benjamin-Dobell** [comment]
UI is client-side except for the callbacks. For example, if you write in an input field, other players cannot see what you're writing.

As suggested above, if you wish to request functionality (or report bugs), there's now an official place to do so.
