### ISSUE TITLE
Undocumented Functions: spawnObjectData() & getData()

### ISSUE THREAD

**Issue by Olliebrown** [Berserk-Games/Tabletop-Simulator-API#58]
V 12.14.2 was released on 5/25/2020 and lists some new functions in its [patch notes](https://www.tabletopsimulator.com/news/patch-notes/v12-4-0-line-tool-revamp-ghost-preview-tags-physics-improvements-and-more) that are not yet documented (as far as I can tell):

- **Object.getData():** the same thing as getJson() except it works with Lua tables so you don't have to convert to/from JSON
- **spawnObjectData():** Similar to spawnObjectJSON(), example `spawnObjectData({ data = Object.GetData()})`

I am in no position to document these myself but I'm very intrigued by them and I wanted to put it on the radar here to see if someone can offer up official documentation beyond the simplistic mention in the patch notes.  I would much rather get the official word than spend time reverse engineering them! ;-)

**Comment by Benjamin-Dobell** [comment]
Closed by https://github.com/Berserk-Games/Tabletop-Simulator-API/pull/59 and https://github.com/Berserk-Games/Tabletop-Simulator-API/pull/110 (https://github.com/Berserk-Games/Tabletop-Simulator-API/commit/25fba90acd912306e7d99d2211824eb2233fe391).

**Comment by Olliebrown** [comment]
Awesome!  Thanks.
