### ISSUE TITLE
Is there any way to update a workshop mod through a script?

### ISSUE THREAD

**Issue by waterfoul** [Berserk-Games/Tabletop-Simulator-API#61]
I'm trying to start a community project which contains a TTS mod as part of it's output. I've figured out how to build the save file, I determined that the tts saves are actually BSON, and I successfully created a mod using steamcmd. I can't figure out how to update one though. Ideally this would also not require steamcmd since 2faed account are painful in steamcmd

**Comment by Jophire** [comment]
Hello, saw this while looking at a report I made a while back about xml.
While not a direct method to update the workshop mod through a script, you can instead have the workshop mod be a json unpacker that points to your json save output. This is the method I am looking to implement for easier version control for my own workshop mod and so others can take part in its creation if they wish to. I just have it point to the corresponding object on github.


```
--On load we preform a web request of the release candidate/current output.
function onLoad(sd)
	WebRequest.get(target_URL,self,"startUnpacking")
end
--So we don't freeze the table on larger downloads, lets through it into a coroutine.
function startUnpacking(webRequest)
	wr = webRequest
	startLuaCoroutine(self,"UnpackMod")
end
--Now to unpack the mod.
function UnpackMod()
        --Wait for mod to finish downloading
	while wr.download_progress < 1 do
		waitFrames(3)
		print("Downloading")
	end
	js = JSON.decode(wr.text)
	--While there are objects left to spawn in the save, loop over it and spawn each object.
	--	spawnObjectJSON({json=JSON.encode(js[obj])})
	--Destroy the loader after the mod is unpacked from json.
	self.destruct()
	return 1
end

function waitFrames(num_frames)
  for i=0, num_frames, 1 do
    if destroying == true then
      i = num_frames+1
    else
      coroutine.yield(0)
    end
  end
  return 1
end
```

Hope this is helpful to what your trying to do.

**Comment by waterfoul** [comment]
This is an interesting idea since my mod also has a companion website, thanks for the tip

**Comment by nabbydude** [comment]
Looks like your issue pertains to Tabletop Simulator itself, and not the API documentation, which this repo is for. Check out [https://tabletopsimulator.nolt.io/](https://tabletopsimulator.nolt.io/) to submit and vote for bugs, suggestions, and requests for the game itself. If you just have a question about the game, also check out [The Official Tabletop Simulator Discord Server](https://discord.com/invite/tabletopsimulator), the community may be able to answer it.
